services:
  frontend:
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:80
    networks:
      - frontend-net
    restart: unless-stopped
    volumes:
      # ro: read-only
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - db-server
  
  backend:
    build: ./backend
    ports: 
      - ${BACKEND_PORT}:8080
    networks:
      - backend-net
      - frontend-net
    volumes:
      # Dockerfile에서의 디렉터리 구조를 참고. 
      - image-vol:/app/files
    restart: unless-stopped
    depends_on:
      db-server:
        condition: service_healthy
    secrets:
      - db-url
      - db-user
      - db-password
  
  db-server:
    image: mariadb:latest
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - backend-net
    ports:
      - ${DB_PORT}:3306
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
      MARIADB_USER_FILE: /run/secrets/db-user
      MARIADB_PASSWORD_FILE: /run/secrets/db-password
      MARIADB_DATABASE_FILE: /run/secrets/db-name
    secrets:
      - db-root-password
      - db-user
      - db-password
      - db-name
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

secrets:
  db-url:
    file: ./secrets/spring-datasource-url.txt
  db-user:
    file: ./secrets/spring-datasource-user.txt
  db-password:
    file: ./secrets/spring-datasource-password.txt
  db-root-password:
    file: ./secrets/db-root-password.txt
  db-name:
    file: ./secrets/db-name.txt

volumes:
  db-vol:
  image-vol:

networks:
  backend-net:
  frontend-net:
