spring.config.import=optional:configtree:/run/secrets/
spring.datasource.url=${db-url}
spring.datasource.username=${db-user}
spring.datasource.password=${db-password}

# 실제 운영 시에는 이 값은 부적절하겠으나, 여기서는 실습 상의 편의를 위해 다음과 같이 설정함.
spring.jpa.hibernate.ddl-auto=update